---
title: North West Tech Events
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Tech Events in and around the Northwest. A collection of groups, conferences
  and a calendar. Created and maintained by the event organisers.

'
lang: en
author: technwuk
twitter:
  username: technwuk
  card: summary
logo: "/images/bee.png"
google_analytics: UA-63203141-1
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-github-metadata
exclude:
- README.md
- Gemfile
- Gemfile.lock
